use_frameworks!

platform :ios, '10.0'

target 'MasivPushIosSdk_Example' do

  pod 'MasivPushIosSdk', :path => '../MasivPushIosSdk.podspec'

  target 'MasivPushIosSdk_Tests' do
    inherit! :search_paths

    
  end
end
